In [1]:
import pandas as pd
import numpy as np

In [2]:
census = pd.read_csv(
    "../data/raw/census/Indv17_PopulationByLiteracyStatus.csv"
)

In [3]:
census.head()

,prov,dist,gapa,sex,agegrp,provname,dname,gapaname,sexname,agegrpname,rowtotal,a_readwrite,b_readonly,c_noreadwrite,d_notstd
0,0,0,0,0,0,NEPAL,NEPAL,NEPAL,Total,Total,26725295,20377980,114331,6223061,9923
1,0,0,0,0,1,NEPAL,NEPAL,NEPAL,Total,05 Year,568365,465615,7990,91618,3142
2,0,0,0,0,2,NEPAL,NEPAL,NEPAL,Total,06 Year,562745,499890,6313,55555,987
3,0,0,0,0,3,NEPAL,NEPAL,NEPAL,Total,07 Year,534278,494401,4245,35157,475
4,0,0,0,0,4,NEPAL,NEPAL,NEPAL,Total,08 Year,599728,560722,3287,35365,354

In [4]:
census.columns

Index(['prov', 'dist', 'gapa', 'sex', 'agegrp', 'provname', 'dname',
       'gapaname', 'sexname', 'agegrpname', 'rowtotal', 'a_readwrite',
       'b_readonly', 'c_noreadwrite', 'd_notstd'],
      dtype='str')

In [5]:
census.shape

(68625, 15)

In [6]:
census.info()

<class 'pandas.DataFrame'>
RangeIndex: 68625 entries, 0 to 68624
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   prov           68625 non-null  int64
 1   dist           68625 non-null  int64
 2   gapa           68625 non-null  int64
 3   sex            68625 non-null  int64
 4   agegrp         68625 non-null  int64
 5   provname       68625 non-null  str
 6   dname          68625 non-null  str
 7   gapaname       68625 non-null  str
 8   sexname        68625 non-null  str
 9   agegrpname     68625 non-null  str
 10  rowtotal       68625 non-null  int64
 11  a_readwrite    68625 non-null  int64
 12  b_readonly     68625 non-null  int64
 13  c_noreadwrite  68625 non-null  int64
 14  d_notstd       68625 non-null  int64
dtypes: int64(10), str(5)
memory usage: 7.9 MB

In [7]:
print(census["dname"].nunique())

162

In [8]:
print(census["provname"].nunique())

15

In [9]:
print(census["gapaname"].nunique())

820

In [10]:
sorted(census["dname"].unique())

['ACHHAM',
 'ARGHAKHANCHI',
 'Achham',
 'Arghakhanchi',
 'BAGLUNG',
 'BAGMATI',
 'BAITADI',
 'BAJHANG',
 'BAJURA',
 'BANKE',
 'BARA',
 'BARDIYA',
 'BHAKTAPUR',
 'BHOJPUR',
 'Baglung',
 'Baitadi',
 'Bajhang',
 'Bajura',
 'Banke',
 'Bara',
 'Bardiya',
 'Bhaktapur',
 'Bhojpur',
 'CHITAWAN',
 'Chitawan',
 'DADELDHURA',
 'DAILEKH',
 'DANG',
 'DARCHULA',
 'DHADING',
 'DHANKUTA',
 'DHANUSA',
 'DOLAKHA',
 'DOLPA',
 'DOTI',
 'Dadeldhura',
 'Dailekh',
 'Dang',
 'Darchula',
 'Dhading',
 'Dhankuta',
 'Dhanusa',
 'Dolakha',
 'Dolpa',
 'Doti',
 'GANDAKI',
 'GORKHA',
 'GULMI',
 'Gorkha',
 'Gulmi',
 'HUMLA',
 'Humla',
 'ILAM',
 'Ilam',
 'JAJARKOT',
 'JHAPA',
 'JUMLA',
 'Jajarkot',
 'Jhapa',
 'Jumla',
 'KAILALI',
 'KALIKOT',
 'KANCHANPUR',
 'KAPILBASTU',
 'KARNALI',
 'KASKI',
 'KATHMANDU',
 'KAVREPALANCHOK',
 'KHOTANG',
 'Kailali',
 'Kalikot',
 'Kanchanpur',
 'Kapilbastu',
 'Kaski',
 'Kathmandu',
 'Kavrepalanchok',
 'Khotang',
 'LALITPUR',
 'LAMJUNG',
 'LUMBINI',
 'Lalitpur',
 'Lamjung',
 'MADHESH',
 'MAHOTTARI',
 'MAKWANPUR',
 'MANANG',
 'MORANG',
 'MUGU',
 'MUSTANG',
 'MYAGDI',
 'Mahottari',
 'Makwanpur',
 'Manang',
 'Morang',
 'Mugu',
 'Mustang',
 'Myagdi',
 'NAWALPARASI (BARDAGHAT SUSTA EAST)',
 'NAWALPARASI (BARDAGHAT SUSTA WEST)',
 'NEPAL',
 'NUWAKOT',
 'Nawalparasi (Bardaghat Susta East)',
 'Nawalparasi (Bardaghat Susta West)',
 'Nuwakot',
 'OKHALDHUNGA',
 'Okhaldhunga',
 'PALPA',
 'PANCHTHAR',
 'PARBAT',
 'PARSA',
 'PROVINCE - 1',
 'PYUTHAN',
 'Palpa',
 'Panchthar',
 'Parbat',
 'Parsa',
 'Pyuthan',
 'RAMECHHAP',
 'RASUWA',
 'RAUTAHAT',
 'ROLPA',
 'RUKUM (EAST)',
 'RUKUM (WEST)',
 'RUPANDEHI',
 'Ramechhap',
 'Rasuwa',
 'Rautahat',
 'Rolpa',
 'Rukum (East)',
 'Rukum (West)',
 'Rupandehi',
 'SALYAN',
 'SANKHUWASABHA',
 'SAPTARI',
 'SARLAHI',
 'SINDHULI',
 'SINDHUPALCHOK',
 'SIRAHA',
 'SOLUKHUMBU',
 'SUDURPASCHIM',
 'SUNSARI',
 'SURKHET',
 'SYANGJA',
 'Salyan',
 'Sankhuwasabha',
 'Saptari',
 'Sarlahi',
 'Sindhuli',
 'Sindhupalchok',
 'Siraha',
 'Solukhumbu',
 'Sunsari',
 'Surkhet',
 'Syangja',
 'TANAHU',
 'TAPLEJUNG',
 'TERHATHUM',
 'Tanahu',
 'Taplejung',
 'Terhathum',
 'UDAYAPUR',
 'Udayapur']

In [11]:
census[census["prov"] == 0][["prov", "dist", "gapa", "provname", "dname"]].drop_duplicates()

   prov  dist  gapa provname  dname
0     0     0     0    NEPAL  NEPAL

In [12]:
census[
    (census["prov"] != 0) &
    (census["dist"] == 0)
][["prov","dist","gapa","provname","dname"]].drop_duplicates()

       prov  dist  gapa      provname         dname
75        1     0     0  PROVINCE - 1  PROVINCE - 1
12525     2     0     0       MADHESH       MADHESH
24000     3     0     0       BAGMATI       BAGMATI
34950     4     0     0       GANDAKI       GANDAKI
43050     5     0     0       LUMBINI       LUMBINI
53100     6     0     0       KARNALI       KARNALI
60600     7     0     0  SUDURPASCHIM  SUDURPASCHIM

In [13]:
census[
    (census["dist"] != 0) &
    (census["gapa"] == 0)
][["prov","dist","gapa","provname","dname"]].drop_duplicates().head(20)

       prov  dist  gapa    provname          dname
150       1     1     0  Province-1      TAPLEJUNG
975       1     2     0  Province-1  SANKHUWASABHA
1875      1     3     0  Province-1     SOLUKHUMBU
2625      1     4     0  Province-1    OKHALDHUNGA
3375      1     5     0  Province-1        KHOTANG
4275      1     6     0  Province-1        BHOJPUR
5100      1     7     0  Province-1       DHANKUTA
5775      1     8     0  Province-1      TERHATHUM
6375      1     9     0  Province-1      PANCHTHAR
7125      1    10     0  Province-1           ILAM
8025      1    11     0  Province-1          JHAPA
9300      1    12     0  Province-1         MORANG
10725     1    13     0  Province-1        SUNSARI
11775     1    14     0  Province-1       UDAYAPUR
12600     2    15     0     Madhesh        SAPTARI
14100     2    16     0     Madhesh         SIRAHA
15525     2    17     0     Madhesh        DHANUSA
17025     2    18     0     Madhesh      MAHOTTARI
18300     2    19     0     Madhesh        SARLAHI
19950     2    20     0     Madhesh       RAUTAHAT

In [14]:
census[
    census["gapa"] != 0
][["prov","dist","gapa","provname","dname","gapaname"]].head(20)

     prov  dist  gapa    provname      dname                gapaname
225     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
226     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
227     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
228     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
229     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
230     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
231     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
232     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
233     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
234     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
235     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
236     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
237     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
238     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
239     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
240     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
241     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
242     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
243     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika
244     1     1     1  Province-1  Taplejung  Phaktanlung Gaunpalika

In [15]:
districts = (
    census[
        (census["dist"] != 0) &
        (census["gapa"] == 0)
    ][["prov", "provname", "dist", "dname"]]
    .drop_duplicates()
    .sort_values(["prov", "dist"])
    .reset_index(drop=True)
)

districts.head()

   prov    provname  dist          dname
0     1  Province-1     1      TAPLEJUNG
1     1  Province-1     2  SANKHUWASABHA
2     1  Province-1     3     SOLUKHUMBU
3     1  Province-1     4    OKHALDHUNGA
4     1  Province-1     5        KHOTANG

In [16]:
print("Rows:", len(districts))
print("Unique districts:", districts["dname"].nunique())
print("Unique district codes:", districts["dist"].nunique())

Rows: 77
Unique districts: 77
Unique district codes: 77

In [17]:
print(districts["provname"].unique())

<StringArray>
[  'Province-1',      'Madhesh',      'Bagmati',      'Gandaki',
      'Lumbini',      'Karnali', 'Sudurpaschim']
Length: 7, dtype: str

In [18]:
province_lookup = {
    "Province-1": "Koshi",
    "PROVINCE - 1": "Koshi",
    "Madhesh": "Madhesh",
    "Bagmati": "Bagmati",
    "Gandaki": "Gandaki",
    "Lumbini": "Lumbini",
    "Karnali": "Karnali",
    "Sudurpaschim": "Sudurpashchim"
}

districts["province_std"] = districts["provname"].replace(province_lookup)

In [19]:
districts["province_std"].unique()

<StringArray>
['Koshi', 'Madhesh', 'Bagmati', 'Gandaki', 'Lumbini', 'Karnali',
 'Sudurpashchim']
Length: 7, dtype: str

In [20]:
districts["district_std"] = districts["dname"].str.title()

In [21]:
canonical_districts = districts[
    [
        "prov",
        "province_std",
        "dist",
        "district_std"
    ]
].rename(columns={
    "prov": "province_code",
    "province_std": "province_name",
    "dist": "district_code",
    "district_std": "district_name"
})

canonical_districts.head()

   province_code province_name  district_code  district_name
0              1         Koshi              1      Taplejung
1              1         Koshi              2  Sankhuwasabha
2              1         Koshi              3     Solukhumbu
3              1         Koshi              4    Okhaldhunga
4              1         Koshi              5        Khotang

In [22]:
canonical_districts.to_csv(
    "../data/lookup/canonical_districts.csv",
    index=False
)

In [23]:
local_levels = (
    census[
        census["gapa"] != 0
    ][
        [
            "prov",
            "dist",
            "gapa",
            "provname",
            "dname",
            "gapaname"
        ]
    ]
    .drop_duplicates()
    .sort_values(["prov", "dist", "gapa"])
    .reset_index(drop=True)
)

In [24]:
print("Rows:", len(local_levels))
print("Unique local codes:", local_levels["gapa"].nunique())

Rows: 830
Unique local codes: 21

In [25]:
print(census["gapa"].min())
print(census["gapa"].max())

0
99

In [26]:
sorted(census["gapa"].unique())

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9),
 np.int64(10),
 np.int64(11),
 np.int64(12),
 np.int64(13),
 np.int64(14),
 np.int64(15),
 np.int64(16),
 np.int64(17),
 np.int64(18),
 np.int64(19),
 np.int64(20),
 np.int64(99)]

In [27]:
census[
    (census["dist"] == 1) &
    (census["gapa"] != 0)
][["dist","dname","gapa","gapaname"]].drop_duplicates()

     dist      dname  gapa                        gapaname
225     1  Taplejung     1          Phaktanlung Gaunpalika
300     1  Taplejung     2           Mikwakhola Gaunpalika
375     1  Taplejung     3            Meringden Gaunpalika
450     1  Taplejung     4           Maiwakhola Gaunpalika
525     1  Taplejung     5     Aatharai Tribeni Gaunpalika
600     1  Taplejung     6          Phungling Municipality
675     1  Taplejung     7  Pathivara Yangwarak Gaunpalika
750     1  Taplejung     8            Sirijanga Gaunpalika
825     1  Taplejung     9             Sidingba Gaunpalika
900     1  Taplejung    99                   INSTITUTIONAL

In [28]:
local_levels = (
    census[census["gapa"] != 0][
        ["prov","dist","gapa","provname","dname","gapaname"]
    ]
    .drop_duplicates()
)

print(len(local_levels))

830

In [29]:
local_levels = (
    census[
        (census["gapa"] != 0) &
        (census["gapa"] != 99)
    ][
        [
            "prov",
            "dist",
            "gapa",
            "provname",
            "dname",
            "gapaname"
        ]
    ]
    .drop_duplicates()
    .sort_values(["prov","dist","gapa"])
    .reset_index(drop=True)
)

In [30]:
print(len(local_levels))

753

In [31]:
local_levels.duplicated(
    subset=["prov","dist","gapa"]
).sum()

np.int64(0)

In [32]:
local_levels["province_name"] = local_levels["provname"].replace(province_lookup)

local_levels["district_name"] = local_levels["dname"].str.title()

local_levels["local_level_name"] = local_levels["gapaname"].str.title()

canonical_local_levels = (
    local_levels[
        [
            "prov",
            "province_name",
            "dist",
            "district_name",
            "gapa",
            "local_level_name"
        ]
    ]
    .rename(columns={
        "prov": "province_code",
        "dist": "district_code",
        "gapa": "local_level_code"
    })
)

canonical_local_levels.to_csv(
    "../data/lookup/canonical_local_levels.csv",
    index=False
)